import { build } from 'vite'
import path from 'node:path'
import fs from 'node:fs'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { loadFacets, facetRoutes } from './facet-routes.mjs'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')

const staticPages = [
  { name: 'main', entry: 'src/entry-server-main.tsx', html: 'dist/index.html' },
  { name: 'privacy', entry: 'src/entry-server-privacy.tsx', html: 'dist/privacy/index.html' },
  { name: 'playbook', entry: 'src/entry-server-playbook.tsx', html: 'dist/playbook/index.html' },
  { name: 'methodology', entry: 'src/entry-server-methodology.tsx', html: 'dist/methodology/index.html' },
  { name: 'explore', entry: 'src/entry-server-explore.tsx', html: 'dist/explore/index.html' },
  { name: 'removal', entry: 'src/entry-server-removal.tsx', html: 'dist/removal/index.html' },
  { name: 'signals', entry: 'src/entry-server-signals.tsx', html: 'dist/signals/index.html' },
]

const facets = loadFacets()
const routes = facetRoutes(facets)

const ssrOutDir = 'dist-ssr'

// One shared SSR bundle serves every facet page (entry-server-facet.tsx's
// render(sectorKey, regionKey) is called once per facet below) rather than
// building 48 near-identical bundles.
await build({
  root,
  logLevel: 'warn',
  build: {
    ssr: true,
    outDir: ssrOutDir,
    emptyOutDir: true,
    rollupOptions: {
      input: {
        ...Object.fromEntries(staticPages.map((p) => [p.name, path.resolve(root, p.entry)])),
        facet: path.resolve(root, 'src/entry-server-facet.tsx'),
      },
      output: { format: 'es', entryFileNames: '[name].mjs' },
    },
  },
})

// Vercel Web Analytics. Served from our own origin (/_vercel/insights/*) once
// the feature is enabled on the Vercel project, so vercel.json's
// `script-src 'self'` needs no exception — any third-party analytics host
// would have needed one, which is most of why this one was chosen. Cookieless
// and aggregate; the privacy policy describes it under "Analytics".
//
// Injected at build time rather than committed into each page's index.html
// because the 48 facet shells are generated by generate-facet-pages.mjs, and
// this is the one place every page — static and generated alike — passes
// through. In `npm run dev` the tag is absent entirely (this script only runs
// on build), so local dev never requests a route that doesn't exist there.
const ANALYTICS_TAG = '<script defer src="/_vercel/insights/script.js"></script>'

const SITE_URL = 'https://placementscout.vercel.app'
const OG_IMAGE = `${SITE_URL}/og-image.png`

// Per-route share cards. A page shared as often as /signals/ deserves a card
// that states its own numbers rather than the home page's headline; anything
// without an entry falls back to the generic one.
const OG_IMAGE_BY_PATH = {
  "/signals/": `${SITE_URL}/og-signals.png`,
}

// Open Graph / Twitter Card tags, derived from each page's own <title> and
// meta description rather than hand-written per page. W-2 originally wrote
// them into index.html by hand, which is why for two weeks the home page had
// a share card and the other 54 routes had none — including /signals/, the
// one being posted. Deriving them here means a new page cannot be added
// without them.
//
// The home page's hand-written block was deleted in favour of this; the tags
// it produces there are identical because og:title/og:description were
// already exact copies of the title and description.
function socialTags(htmlPath, title, description) {
  const rel = path
    .relative(path.resolve(root, 'dist'), htmlPath)
    .replace(/index\.html$/, '')
    .replace(/\\/g, '/')
  const url = `${SITE_URL}/${rel}`
  const image = OG_IMAGE_BY_PATH[`/${rel}`] ?? OG_IMAGE
  const tags = [
    ['property', 'og:type', 'website'],
    ['property', 'og:site_name', 'Placement Scout'],
    ['property', 'og:url', url],
    ['property', 'og:title', title],
    ['property', 'og:description', description],
    ['property', 'og:image', image],
    ['property', 'og:image:width', '1200'],
    ['property', 'og:image:height', '630'],
    ['name', 'twitter:card', 'summary_large_image'],
    ['name', 'twitter:title', title],
    ['name', 'twitter:description', description],
    ['name', 'twitter:image', image],
  ]
  return tags.map(([attr, key, value]) => `    <meta ${attr}="${key}" content="${value}" />`).join('\n')
}

function injectRoot(htmlPath, html) {
  const template = fs.readFileSync(htmlPath, 'utf-8')
  const rootDivPattern = /<div id="root"([^>]*)><\/div>/
  if (!rootDivPattern.test(template)) {
    throw new Error(`Could not find the empty root div placeholder in ${htmlPath}`)
  }
  let out = template.replace(rootDivPattern, (_match, attrs) => `<div id="root"${attrs}>${html}</div>`)

  // Collapse the source's line wrapping — these values become single-line
  // attribute content, and an unnormalised newline inside content="" renders
  // as a literal newline in the card text.
  const collapse = (s) => s.replace(/\s+/g, ' ').trim()
  const titleMatch = out.match(/<title>([\s\S]*?)<\/title>/)
  const descMatch = out.match(/<meta\s+name="description"\s+content="([\s\S]*?)"\s*\/?>/)
  if (!titleMatch) throw new Error(`No <title> to build share tags from in ${htmlPath}`)
  if (!descMatch) throw new Error(`No meta description to build share tags from in ${htmlPath}`)
  if (!out.includes('property="og:')) {
    out = out.replace(
      '</head>',
      `${socialTags(htmlPath, collapse(titleMatch[1]), collapse(descMatch[1]))}\n  </head>`
    )
  }

  if (!out.includes(ANALYTICS_TAG)) {
    if (!out.includes('</head>')) {
      throw new Error(`Could not find </head> to inject the analytics tag into ${htmlPath}`)
    }
    out = out.replace('</head>', `    ${ANALYTICS_TAG}\n  </head>`)
  }
  fs.writeFileSync(htmlPath, out)
}

for (const page of staticPages) {
  const modPath = path.resolve(root, ssrOutDir, `${page.name}.mjs`)
  const mod = await import(pathToFileURL(modPath).href)
  injectRoot(path.resolve(root, page.html), mod.render())
  console.log(`Prerendered ${page.name} -> ${page.html}`)
}

const facetMod = await import(pathToFileURL(path.resolve(root, ssrOutDir, 'facet.mjs')).href)
for (const route of routes) {
  const html = facetMod.render(route.sectorKey, route.regionKey)
  injectRoot(path.resolve(root, 'dist', route.dir, 'index.html'), html)
}
console.log(`Prerendered ${routes.length} facet pages`)

// W-8: sitemap.xml + robots.txt. Every URL here is real, indexable, unique
// server-rendered content (W-1/W-6) — no per-firm pages exist to exclude
// (W-7's premise doesn't apply yet; this list needs revisiting if that
// changes).
const indexablePaths = [
  '/', '/privacy/', '/playbook/', '/methodology/', '/explore/', '/removal/', '/signals/',
  ...routes.map((r) => `/${r.dir}/`),
]
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${indexablePaths.map((p) => `  <url><loc>${SITE_URL}${p}</loc></url>`).join('\n')}
</urlset>
`
fs.writeFileSync(path.resolve(root, 'dist/sitemap.xml'), sitemap)

const robots = `User-agent: *
Allow: /

Sitemap: ${SITE_URL}/sitemap.xml
`
fs.writeFileSync(path.resolve(root, 'dist/robots.txt'), robots)
console.log(`Wrote sitemap.xml (${indexablePaths.length} URLs) and robots.txt`)
