import path from 'path'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { loadFacets, facetRoutes } from './scripts/facet-routes.mjs'

// Facet page HTML shells (explore/<sector>/<region>/index.html) are
// generated by scripts/generate-facet-pages.mjs, which must run before
// `vite build` — see package.json's build script. This just needs to know
// their names/paths to add them to the multi-page input map below.
const facetInputs = Object.fromEntries(
  facetRoutes(loadFacets()).map((r) => [r.name, path.resolve(__dirname, r.dir, 'index.html')]),
)

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), tailwindcss()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  build: {
    rollupOptions: {
      input: {
        main: path.resolve(__dirname, 'index.html'),
        privacy: path.resolve(__dirname, 'privacy/index.html'),
        playbook: path.resolve(__dirname, 'playbook/index.html'),
        methodology: path.resolve(__dirname, 'methodology/index.html'),
        explore: path.resolve(__dirname, 'explore/index.html'),
        removal: path.resolve(__dirname, 'removal/index.html'),
        ...facetInputs,
      },
    },
  },
})
